### ISSUE TITLE
Create two modes of applying blocks : old push and new pull mode

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-wallet-legacy#262]
# Context

We want to have two modes of operation when it comes to consuming blocks from the node. The old one (well tested, but introducing coupling) based on readerT mechanism and in essence being the push mechanism with all the responsibility of tracking consumed blocks laying on the node side. The new pull mechanism is based on active wallet side, polling tip of the block and requesting proper blocks (it is not fully tested but introduces decoupling from the node)  

# Decision

For the sake of containing possible risks we are going to introduce optional flag that can switch on pull mechanism. In default, it is going to be old readerT (push mechanism)   

# Acceptance Criterias

1. There must be possibility to run wallet with either push or pull mechanism. 

---

# Development Plan

- [ ] add the flag that switch on pull mechanism. otherwise old push, readerT based mechanism, is active
 

# PR

| Number   | Base      |
| ---      | ---       |
| #177        | `develop` |

# QA 

| Criteria | Coverage |
| ---      | ---      |
| ?        | -        |

---

# Retrospective

**Comment by KtorZ** [comment]
I'll close this in favor of #88. I know we open this ticket as a way to split the work of #88 but this is getting a bit out of hand. 
Hence, let's "close the topic" of decoupling in its current state but on a side-branch on which we can continue experimenting if needed and adjusting the code until we think we have something stable enough to make it to `develop`.

Also, since we won't be releasing any of this into the next 3 releases, there's no particular rush in having it inside `develop` _now_. So we'll come to that eventually and now that we have a better understanding of the situation and what we are facing, we can adjust and adapt or, actually, directly go implementing the future Haskell or Rust protocol and stop bothering with the legacy code.
