### ISSUE TITLE
Remove readerT mechanism that uses MonadBListener from the wallet and fetches blocks through the diffusion layer

### ISSUE THREAD

**Issue by paweljakubas** [input-output-hk/cardano-wallet-legacy#88]
# Context

In order to operate and maintain its own UTxO state, the wallet applies blocks successively and extract information from them. This current implementation has been described in:

https://github.com/input-output-hk/cardano-wallet/wiki/ApplyingBlocks-Rollback-After-Decoupling-Byron

Here, we can see how blocks are received through a shared environment mechanism between the wallet and its underlying node. This creates strong memory coupling between both processes.

# Decision

We want to get rid of this shared environment (through `readerT`) and rely on the diffusion layer capabilities instead. This includes refactoring the current `BListener`, the overall block application and rollbacks mechanism. Note that the wallet currently receives `Blund`s from the `BListener` instead of mere `Blocks`. However, `Undo`s from `Blunds` are only used to retrieve some transaction Metadata which are otherwise available in (and will have to be looked up from) the `UTxO` maintained by the wallet. 

# Acceptance Criterias

1. The `BListener` _mustn't_ use any strong memory coupling to retrieve blocks from the node
2. The `BListener` _must_ use the diffusion layer to receive blocks from the node
3. The diffusion layer interface _mustn't_ change

---

# Development Plan

- [x] getBlocks and requestTip support is added in diffusion layer
- [x] The additional thread is instantiated that is responsible for downloading blocks from the node
- [x] The added mechanism is based on pull paradigm, ie., the wallet is the initiator for pulling blocks, that takes responsibility the blocks are in line with what the trusted node has
- [x] The same resolved blocks are created using the added mechanism as it is in case of old mechanism
- [x] apply blocks part of old mechanism is commented out
- [x] All integration tests pass
- [x] the pull mechanism is documented in the wiki
- [x] verify if occasionally dedicated thread for applying blocks got stuck and if yes make it stable 
- [x] rollback mechanism is proposed and added to wiki
- [x] data needed to realize pull mechanism is taken from wallet state rather than by invoke params (ie., consumed block headers can be retrieved from wallet state)
- [x] simplify tickDiffusionFunction further and check `processBlockTx` (utxo should probably be updated from the oldest to youngest block)
- [ ] document manual testing in `node-attached-to-mainnet-with-wallet` setup
- [ ] check restoration in `node-attached-to-mainnet-with-wallet` setup 
- [ ] check backfilling  in `node-attached-to-mainnet-with-wallet` setup
- [ ] check calculation of the time in the block - probably should be determined basing on the slotId and genesis block. Right now current time is used and we do not witness any problems with this
- [ ] add a dedicated DSL extension for this expectNextEpochEventually in order to test in more than two epochs
- [ ] remove reflection instance Scc
- [ ] not needed old code that served readerT mechanism is removed
 

# PR

| Number   | Base      |
| ---      | ---       |
| #177        | `develop` |

# QA 

| Criteria | Coverage |
| ---      | ---      |
| ?        | -        |

---

# Retrospective

**Comment by KtorZ** [comment]
Following up on: https://github.com/input-output-hk/cardano-wallet/issues/262#issuecomment-459728814

@piotr-iohk. I am closing this. This _exploratory_ ticket has been there for a while and @paweljakubas did achieve quite a nice job at documenting everything in the wiki and at proposing a prototype solution while also testing its correct behavior against a local cluster and mainnet. 

Still remains, handling rollbacks correctly (which we need to figure out how to test: perhaps by simulating some network disconnection between local clusters), which would require to actually store the last k = 2160 blocks on disk which come with design decision, db choice, serialization representation etc.
While we could go for "duplicating" what's on sl and taking only the bits that are of interest for us, it isn't really consistent with the "getting away from the legacy codebase" approach. 

So here, I am more in favor of "aborting" the end of this and rethink a bit how we want to approach this decoupling moving forward and if we want to decouple on top of the legacy codebase at all... I've merged the result in a side branch `develop-decoupled` to make sure not to loose it.

I'll nevertheless apply an "ABORTED" label on the ticket to clearly states that this hasn't made it to `develop` because of further complication.
